[build]
  command = "npm run build"
  publish = "public"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  targetPort = 3000
  port = 8888
  publish = "public"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200